### ISSUE TITLE
[RU] Discussing glossary and style guide on translation 

### ISSUE THREAD

**Issue by lex111** [gatsbyjs/gatsby-ru#19]
Приветствую @alexandrtovmach @StrikerRUS, давайте тут обсудим как лучше переводить фразы и составим глоссарий.

Например, мне непонятно, почему было решено переводить Note и Tip как "заметка"? Обычно такое переводят как "Примечание" и "Подсказка".

**Comment by alexandrtovmach** [comment]
Немного контекста по "Note" и "Tip" — они будут приведены к общему знаменателю в оригинальном документе в ближайшем будущем (я работаю над линтером, включая валидацию подобных фраз). Использование "Tip" это ошибка в оригинале и не более.

**Почему "заметка"?**
 "Примечание" — звучит слишком официально и не раскрывает сути обоих слов
"Подсказка" — хороший вариант, но смысл немного искажается в сторону того что _без этой информации тебе не обойтись_, но "Note" может содержать просто информацию о дополнительных ресурсах и т.п.

По моему субъективному мнению "заметка" наиболее универсальное слово.

**Comment by lex111** [comment]
Если останется только Note, то тем более "примечание" более подходящее, обычно в переводных (и не только) книгах пишут "Примечание", если нужно пояснить текст. И оно как раз будет больше всего универсальным, поскольку употребляется намного чаще, можно считать своего рода идиому (редко встретишь "Заметка", если такое и пишут, то скорее немного иначе - "На заметку" - и то больше как заголовок в информационной сноске.

> "Примечание" — звучит слишком официально и не раскрывает сути обоих слов

Не сказал, формально может быть, но это наиболее подходящее по смыслу слово (опять-таки если брать словарное значение, то оно "выигрывает" у "Заметки"). Когда-то хотелось употреблять фамильярную форму "ты" вместо "официальной" уважительной "вы". Здесь по-моему похожая ситуация.

Подсказка относилась только к Tip, и оно не выражает необходимости, это дополнительная информация, которую можно и проигнорировать, но лучше этого не делать, т.е. как синоним "рекомендация" или "совет".

**Comment by StrikerRUS** [comment]
Я тоже больше привык видеть слово "примечание" в переводах книг по программированию. Но и против "заметки" я ничего не имею.

**Comment by lex111** [comment]
Считаю, что всё-таки нужно изменить на использование "Примечание", в русскоязычных текстах обычно с помощью него поясняется смысл, поэтому нужно следовать этому. Подготовлю в ближайшее время глоссарий, он будет расширять глоссарий из React.

**Comment by alexandrtovmach** [comment]
2/1, значит используем "Примечание"
